version: "3.7"

# docker-compose is for dev environment

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: base
    command: python3 ./src/app.py
    container_name: api
    image: federated-flask-api
    volumes:
      - ./backend:/usr/src/app/backend
    ports:
      - "5000:5000"
    environment:
      SERVER_ADDR: 0.0.0.0
      PORT: 5000

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: base
    command: npm start
    container_name: client
    image: federated-react-app
    volumes:
      - ./frontend:/usr/src/app/frontend
    ports:
      - "3000:3000"
    environment:
      HOST_ADDR: api
    depends_on:
      - api
# client and api are part of the same network by default
# due to docker-compose.
