version: "3.7"

# docker-compose is for dev environment

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: base
    command: python3 -u ./src/app.py
    container_name: api
    image: federated-flask-api
    volumes:
      - ./backend:/usr/src/app/backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      SERVER_ADDR: 0.0.0.0
      ENVIRONMENT: development
      PORT: 5000
      S3_URL: https://clientmodelbucket.s3.us-east-2.amazonaws.com/
      PYTHONUNBUFFERED: 1

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: base
    command: npm start
    container_name: client
    image: federated-react-app
    volumes:
      - ./frontend:/usr/src/app/frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      HOST_ADDR: api
      S3_URL: https://fedmodelbucket.s3.us-east-2.amazonaws.com
    depends_on:
      - api
# client and api are part of the same network by default
# due to docker-compose.
